// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.API.Data;

#nullable disable

namespace SchoolManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528185555_AddTeacherAssignmentsMenu")]
    partial class AddTeacherAssignmentsMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.API.Models.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("YearLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcademicYearId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarkedBy")
                        .HasColumnType("int");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("MarkedBy");

                    b.HasIndex("PeriodId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int?>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.ClassSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FeePayment", b =>
                {
                    b.Property<int>("FeePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeePaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("CollectedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentFeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FeePaymentId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("StudentFeeId");

                    b.ToTable("FeePayments");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FeeStructure", b =>
                {
                    b.Property<int>("FeeStructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeStructureId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DueDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FeeStructureId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ClassId");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("FeeStructures");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FeeType", b =>
                {
                    b.Property<int>("FeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FeeTypeId");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FileStore", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("FileStores");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Homework", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeworkId"));

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("HomeworkId");

                    b.HasIndex("ClassId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Homeworks");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.HomeworkSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("HomeworkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex("FileId");

                    b.HasIndex("HomeworkId");

                    b.HasIndex("StudentId");

                    b.ToTable("HomeworkSubmissions");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("RouteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "dashboard",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/dashboard",
                            SortOrder = 10,
                            Title = "Dashboard"
                        },
                        new
                        {
                            MenuItemId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "people",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/users",
                            SortOrder = 20,
                            Title = "Users"
                        },
                        new
                        {
                            MenuItemId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "school",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 30,
                            Title = "Academics"
                        },
                        new
                        {
                            MenuItemId = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "badge",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/teachers",
                            SortOrder = 35,
                            Title = "Teachers"
                        },
                        new
                        {
                            MenuItemId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "groups",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/students",
                            SortOrder = 40,
                            Title = "Students"
                        },
                        new
                        {
                            MenuItemId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "schedule",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 50,
                            Title = "Timetable"
                        },
                        new
                        {
                            MenuItemId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "how_to_reg",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 60,
                            Title = "Attendance"
                        },
                        new
                        {
                            MenuItemId = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "assignment",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 70,
                            Title = "Homework"
                        },
                        new
                        {
                            MenuItemId = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "folder",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/files",
                            SortOrder = 80,
                            Title = "Files"
                        },
                        new
                        {
                            MenuItemId = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "settings",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/admin/menu",
                            SortOrder = 90,
                            Title = "Menu Management"
                        },
                        new
                        {
                            MenuItemId = 26,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "tune",
                            IsActive = true,
                            IsDeleted = false,
                            RouteUrl = "/admin/settings",
                            SortOrder = 95,
                            Title = "School Settings"
                        },
                        new
                        {
                            MenuItemId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "class",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 3,
                            RouteUrl = "/academics/classes",
                            SortOrder = 31,
                            Title = "Classes"
                        },
                        new
                        {
                            MenuItemId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "calendar_month",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 3,
                            RouteUrl = "/academics/years",
                            SortOrder = 32,
                            Title = "Academic Years"
                        },
                        new
                        {
                            MenuItemId = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "library_books",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 3,
                            RouteUrl = "/academics/subjects",
                            SortOrder = 33,
                            Title = "Subjects"
                        },
                        new
                        {
                            MenuItemId = 27,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "assignment_ind",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 3,
                            RouteUrl = "/academics/teacher-assignments",
                            SortOrder = 34,
                            Title = "Teacher Assignments"
                        },
                        new
                        {
                            MenuItemId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "person_add",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 6,
                            RouteUrl = "/students/new",
                            SortOrder = 41,
                            Title = "New Admission"
                        },
                        new
                        {
                            MenuItemId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "list",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 6,
                            RouteUrl = "/students/list",
                            SortOrder = 42,
                            Title = "Student List"
                        },
                        new
                        {
                            MenuItemId = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "edit_calendar",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 9,
                            RouteUrl = "/timetable/setup",
                            SortOrder = 51,
                            Title = "Timetable Setup"
                        },
                        new
                        {
                            MenuItemId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "event",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 9,
                            RouteUrl = "/timetable/view",
                            SortOrder = 52,
                            Title = "View Timetable"
                        },
                        new
                        {
                            MenuItemId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "check_circle",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 12,
                            RouteUrl = "/attendance/mark",
                            SortOrder = 61,
                            Title = "Mark Attendance"
                        },
                        new
                        {
                            MenuItemId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "visibility",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 12,
                            RouteUrl = "/attendance/view",
                            SortOrder = 62,
                            Title = "View Attendance"
                        },
                        new
                        {
                            MenuItemId = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "edit_note",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 15,
                            RouteUrl = "/homework/assign",
                            SortOrder = 71,
                            Title = "Assign Homework"
                        },
                        new
                        {
                            MenuItemId = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "menu_book",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 15,
                            RouteUrl = "/homework/list",
                            SortOrder = 72,
                            Title = "Diary / Homework"
                        },
                        new
                        {
                            MenuItemId = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "payments",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 75,
                            Title = "Fees"
                        },
                        new
                        {
                            MenuItemId = 21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "settings",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 20,
                            RouteUrl = "/fees/setup",
                            SortOrder = 76,
                            Title = "Fee Setup"
                        },
                        new
                        {
                            MenuItemId = 22,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "receipt",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 20,
                            RouteUrl = "/fees/student-fees",
                            SortOrder = 77,
                            Title = "Student Fees"
                        },
                        new
                        {
                            MenuItemId = 23,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "bar_chart",
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = 20,
                            RouteUrl = "/fees/report",
                            SortOrder = 78,
                            Title = "Fee Report"
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.MenuRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("MenuItemId", "RoleId")
                        .IsUnique();

                    b.ToTable("MenuRolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            MenuItemId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            MenuItemId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            MenuItemId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 5,
                            MenuItemId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 6,
                            MenuItemId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 7,
                            MenuItemId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            MenuItemId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            MenuItemId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            MenuItemId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            MenuItemId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            MenuItemId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            MenuItemId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            MenuItemId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            MenuItemId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            MenuItemId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            MenuItemId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            MenuItemId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            MenuItemId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            MenuItemId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            MenuItemId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            MenuItemId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            MenuItemId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            MenuItemId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            MenuItemId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            MenuItemId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            MenuItemId = 9,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            MenuItemId = 9,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 29,
                            MenuItemId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            MenuItemId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            MenuItemId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            MenuItemId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 33,
                            MenuItemId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            MenuItemId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            MenuItemId = 11,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 36,
                            MenuItemId = 11,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 37,
                            MenuItemId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 38,
                            MenuItemId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            MenuItemId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            MenuItemId = 12,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 41,
                            MenuItemId = 12,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 42,
                            MenuItemId = 13,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 43,
                            MenuItemId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            MenuItemId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            MenuItemId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 46,
                            MenuItemId = 14,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 47,
                            MenuItemId = 14,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 48,
                            MenuItemId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 49,
                            MenuItemId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            MenuItemId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 51,
                            MenuItemId = 15,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            MenuItemId = 15,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 53,
                            MenuItemId = 16,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 54,
                            MenuItemId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 55,
                            MenuItemId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 56,
                            MenuItemId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 57,
                            MenuItemId = 17,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 58,
                            MenuItemId = 17,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 59,
                            MenuItemId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 60,
                            MenuItemId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            MenuItemId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            MenuItemId = 18,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 63,
                            MenuItemId = 18,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 64,
                            MenuItemId = 18,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 77,
                            MenuItemId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 78,
                            MenuItemId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            MenuItemId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 85,
                            MenuItemId = 27,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 79,
                            MenuItemId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 80,
                            MenuItemId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 81,
                            MenuItemId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 65,
                            MenuItemId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 82,
                            MenuItemId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 83,
                            MenuItemId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            MenuItemId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 67,
                            MenuItemId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            MenuItemId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 69,
                            MenuItemId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 70,
                            MenuItemId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 71,
                            MenuItemId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 72,
                            MenuItemId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 73,
                            MenuItemId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            MenuItemId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 75,
                            MenuItemId = 23,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 76,
                            MenuItemId = 23,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodNo")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            PeriodId = 1,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 90, DateTimeKind.Utc).AddTicks(8068),
                            EndTime = new TimeOnly(8, 40, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 1",
                            PeriodNo = 1,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            PeriodId = 2,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1011),
                            EndTime = new TimeOnly(9, 20, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 2",
                            PeriodNo = 2,
                            StartTime = new TimeOnly(8, 40, 0)
                        },
                        new
                        {
                            PeriodId = 3,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1020),
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 3",
                            PeriodNo = 3,
                            StartTime = new TimeOnly(9, 20, 0)
                        },
                        new
                        {
                            PeriodId = 4,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1024),
                            EndTime = new TimeOnly(10, 20, 0),
                            IsActive = true,
                            IsBreak = true,
                            IsDeleted = false,
                            PeriodName = "Break",
                            PeriodNo = 4,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            PeriodId = 5,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1026),
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 4",
                            PeriodNo = 5,
                            StartTime = new TimeOnly(10, 20, 0)
                        },
                        new
                        {
                            PeriodId = 6,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1028),
                            EndTime = new TimeOnly(11, 40, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 5",
                            PeriodNo = 6,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            PeriodId = 7,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 52, 91, DateTimeKind.Utc).AddTicks(1032),
                            EndTime = new TimeOnly(12, 20, 0),
                            IsActive = true,
                            IsBreak = false,
                            IsDeleted = false,
                            PeriodName = "Period 6",
                            PeriodNo = 7,
                            StartTime = new TimeOnly(11, 40, 0)
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 742, DateTimeKind.Utc).AddTicks(9851),
                            IsActive = true,
                            RoleName = "superadmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 743, DateTimeKind.Utc).AddTicks(1704),
                            IsActive = true,
                            RoleName = "admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 743, DateTimeKind.Utc).AddTicks(1710),
                            IsActive = true,
                            RoleName = "principal"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 743, DateTimeKind.Utc).AddTicks(1712),
                            IsActive = true,
                            RoleName = "teacher"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 743, DateTimeKind.Utc).AddTicks(1716),
                            IsActive = true,
                            RoleName = "parent"
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 55, 51, 743, DateTimeKind.Utc).AddTicks(1719),
                            IsActive = true,
                            RoleName = "staff"
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.SchoolSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FridayBreakAllowed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("FridayBreakEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("FridayBreakStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("FridayEndTime")
                        .HasColumnType("time");

                    b.Property<int>("FridayGapMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("FridayStartTime")
                        .HasColumnType("time");

                    b.Property<int>("FridayTotalPeriods")
                        .HasColumnType("int");

                    b.Property<string>("HolidaysJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPeriodDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxPeriodsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MinPeriodDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("RegularBreakAllowed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("RegularBreakEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("RegularBreakStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("RegularEndTime")
                        .HasColumnType("time");

                    b.Property<int>("RegularGapMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("RegularStartTime")
                        .HasColumnType("time");

                    b.Property<int>("RegularTotalPeriods")
                        .HasColumnType("int");

                    b.Property<bool>("SundayEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("SundayEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SundayStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchoolSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FridayBreakAllowed = false,
                            FridayBreakEnd = new TimeOnly(10, 10, 0),
                            FridayBreakStart = new TimeOnly(10, 0, 0),
                            FridayEndTime = new TimeOnly(11, 30, 0),
                            FridayGapMinutes = 0,
                            FridayStartTime = new TimeOnly(8, 0, 0),
                            FridayTotalPeriods = 4,
                            HolidaysJson = "[]",
                            MaxPeriodDurationMinutes = 60,
                            MaxPeriodsPerDay = 10,
                            MinPeriodDurationMinutes = 20,
                            RegularBreakAllowed = true,
                            RegularBreakEnd = new TimeOnly(10, 20, 0),
                            RegularBreakStart = new TimeOnly(10, 0, 0),
                            RegularEndTime = new TimeOnly(13, 0, 0),
                            RegularGapMinutes = 0,
                            RegularStartTime = new TimeOnly(8, 0, 0),
                            RegularTotalPeriods = 6,
                            SundayEnabled = false,
                            SundayEndTime = new TimeOnly(13, 0, 0),
                            SundayStartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.SchoolTimetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TimetableId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolTimetables");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("AdmissionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhotoFileId")
                        .HasColumnType("int");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("AdmissionNo")
                        .IsUnique();

                    b.HasIndex("PhotoFileId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentClassEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClassEnrollments");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentFee", b =>
                {
                    b.Property<int>("StudentFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentFeeId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FeeStructureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StudentFeeId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("FeeStructureId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentFees");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentGuardian", b =>
                {
                    b.Property<int>("GuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardianId"));

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GuardianId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentGuardians");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@school.com",
                            FullName = "Super Admin",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Admin@123",
                            PasswordHash = "$2a$11$Z.axpTf6NS4JdKfnywW0X.EhpZwUm/kELo5kU5cnCtYFhjoT.hFcy",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Attendance", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", "MarkedByUser")
                        .WithMany()
                        .HasForeignKey("MarkedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("MarkedByUser");

                    b.Navigation("Period");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Class", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.AcademicYear", null)
                        .WithMany("Classes")
                        .HasForeignKey("AcademicYearId");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.ClassSubject", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FeePayment", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.User", "CollectedByUser")
                        .WithMany()
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.StudentFee", "StudentFee")
                        .WithMany("Payments")
                        .HasForeignKey("StudentFeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectedByUser");

                    b.Navigation("StudentFee");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FeeStructure", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Class");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.FileStore", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Homework", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.FileStore", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("SchoolManagement.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("File");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.HomeworkSubmission", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.FileStore", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("SchoolManagement.API.Models.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.MenuItem", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.MenuRolePermission", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.MenuItem", "MenuItem")
                        .WithMany("MenuRolePermissions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Role", "Role")
                        .WithMany("MenuRolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.RefreshToken", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.SchoolTimetable", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Class");

                    b.Navigation("Period");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Student", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.FileStore", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoFileId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentClassEnrollment", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.AcademicYear", "AcademicYear")
                        .WithMany("Enrollments")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentFee", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.FeeStructure", "FeeStructure")
                        .WithMany()
                        .HasForeignKey("FeeStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("FeeStructure");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentGuardian", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Student", "Student")
                        .WithMany("Guardians")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.User", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.AcademicYear", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Class", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Homework", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.MenuItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuRolePermissions");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Role", b =>
                {
                    b.Navigation("MenuRolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Guardians");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.StudentFee", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("SchoolManagement.API.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
