// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.API.Data;

#nullable disable

namespace SchoolManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602000000_AddExamModule")]
    partial class AddExamModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // NOTE: This file is intentionally left as a stub.
            // Run `dotnet ef migrations add` for the next migration to regenerate
            // the full model snapshot automatically.
        }
    }
}
